[versions]
kotlin = "1.8.0"
coroutines = "1.6.4"
compose = "1.3.0"
jproc = "2.8.2"
turtle = "0.8.0"

[libraries]
stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
jproc = { module = "org.buildobjects:jproc", version.ref = "jproc" }
turtle = { module = "com.lordcodes.turtle:turtle", version.ref = "turtle" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutines" }

[plugins]